version: '3.9'

services:
  app:
    image: ghcr.io/yude/shadowbanalerts-docker:master
    container_name: shadowban-alerts
    build: .
    volumes:
      - type: bind
        source: './ShadowbanAlerts.json'
        target: '/app/ShadowbanAlerts.json'
    environment:
      - TZ=Asia/Tokyo
      - SCREEN_NAMES=@yude_jp
      # - MENTION_TO=
      - WEBHOOK_URL=https://discord.com/api/webhooks/1100176149528727632/iR6502lXJTgzWqmjh189aEB19vkxZNKNiszcI_4xSUa-YR-ckovBIhKMkIANYG3ocJwl
